documentation:
  - "docs/*"

migrations:
  - "django_namespace_permissions/migrations/*"

models:
  - "django_namespace_permissions/models.py"

dependencies:
  - "poetry.lock"

testing:
  - "django_namespace_permissions/tests/*"
  - "testproject/tests/*"
  - "tox.ini"

github_actions:
  - ".github/workflows/*"
