site_name: Django Namespaces
repo_url: https://github.com/terjekv/django_namespaces
docs_dir: docs
site_description: "A permission model for Django through collections of objects."

nav:
  - Home: index.md
  - Installation: installation.md
  - API: api.md

theme:
  name: "material"
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - git-revision-date-localized
  - mkdocstrings
  - autorefs
  - swagger-ui-tag:
      docExpansion: none
      syntaxHighlightTheme: monokai
      tryItOutEnabled: false

markdown_extensions:
  # add attributes to html elements
  - attr_list
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences
  # clickable details
  - pymdownx.details
  # tabbed contents
  - pymdownx.tabbed
  # Highlight code blocks
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
