name: Deploy documentation
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Set up cache
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ github.ref }} 
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: |
            python -m pip install poetry
            poetry install 
            poetry run mkdocs --version

      - name: Build docs, update swagger
        run: poetry run tox -e docs

      - name: Deploy
        run: poetry run mkdocs gh-deploy --force
